#!/bin/bash
# Setup testing on gg tst instance

echo "🧪 SETTING UP TESTING ON GG TST"
echo "================================"
echo ""
echo "This will use the TEST instance, leaving production untouched!"
echo ""

echo "📋 Current gg tst setup:"
echo "- Uses /home/chris/projects/bitstamp-testing/"
echo "- Already has 0.001 BTC limit"
echo "- Completely separate from production"
echo ""

echo "Steps to deploy:"
echo ""
echo "1. Stop any existing test server:"
echo "   ssh ck 'screen -S server-tst -X quit'"
echo ""
echo "2. Pull latest code to test instance:"
echo "   ssh ck 'cd /home/chris/projects/bitstamp-testing && git pull'"
echo ""
echo "3. Copy 1-minute test config:"
echo "   scp /Users/chris/projects/python/btc/claude-bin/test_1min_config.json ck:/home/chris/projects/bitstamp-testing/best_strategy.json"
echo ""
echo "4. Start test server:"
echo "   ssh ck"
echo "   gg tst"
echo "   screen -S server-tst python src/tdr_server.py"
echo ""
echo "5. Connect from Mac:"
echo "   cd /Users/chris/projects/python/btc-testing"
echo "   ./env/bin/python src/tdr.py"
echo "   TDR> resume_auto_trade 0btc short 113793"
echo ""
echo "✅ BENEFITS:"
echo "- Production (gg btc) stays completely untouched"
echo "- See results every minute (60x faster than hourly)"
echo "- Can test aggressively without any risk"
echo "- Easy to stop/restart/modify"